### ISSUE TITLE
立直後可以暗槓

### ISSUE THREAD

**Issue by rasca0027** [rasca0027/Mahjong4RL#168]
立直後可以暗槓，但不能改變聽牌為前提

**Comment by ktc312** [comment]
立直後四開槓/四槓子，會發生什麼事？

**Comment by ktc312** [comment]
----- Tiles in hand -----
🀇 🀇 🀇 🀈 🀈 🀈 🀉 🀉 🀉 🀓 🀔 🀕 🀟  

這樣槓是不是不能槓一萬？
“Disallowable calls either alters the hand's waiting pattern or alters the hand's composition, where tile groupings are changed.” http://arcturus.su/wiki/Riichi#Kan

**Comment by FegnYi-Ed-Liu** [comment]
我們發現，如果手上已經有三張一萬 一個一二三萬 這種牌型，如果立直，不能突然要槓，改牌的型。（不是摸進來的狀況）
