### ISSUE TITLE
Advance_jikaze() bug

### ISSUE THREAD

**Issue by rasca0027** [rasca0027/Mahjong4RL#171]
東風 -> 北風

**Comment by ktc312** [comment]
````
def test_advance_jikaze(self):
        self.assertEqual(self.player.jikaze, Jihai.TON)
        self.player.advance_jikaze()
        self.assertEqual(self.player.jikaze, Jihai.NAN)
        self.player.advance_jikaze()
        self.assertEqual(self.player.jikaze, Jihai.SHAA)
        self.player.advance_jikaze()
        self.assertEqual(self.player.jikaze, Jihai.PEI)
        self.player.advance_jikaze()
        self.assertEqual(self.player.jikaze, Jihai.TON)
```

should be 
````
def test_advance_jikaze(self):
        self.assertEqual(self.player.jikaze, Jihai.TON)
        self.player.advance_jikaze()
        self.assertEqual(self.player.jikaze, Jihai.PEI)
        self.player.advance_jikaze()
        self.assertEqual(self.player.jikaze, Jihai.SHAA)
        self.player.advance_jikaze()
        self.assertEqual(self.player.jikaze, Jihai.NAN)
        self.player.advance_jikaze()
        self.assertEqual(self.player.jikaze, Jihai.TON)
```
