### ISSUE TITLE
Fill in `YAKU_EXCLUDE_TABLE`

### ISSUE THREAD

**Issue by rasca0027** [rasca0027/Mahjong4RL#183]
Fill out `YAKU_EXCLUDE_TABLE` in `yaku_calculator.py` and add corresponding test cases.

**Comment by ktc312** [comment]
是參考這個嗎？ http://arcturus.su/wiki/Yaku_compatibility

然後不需要反過來的對不對？
例如已經有 `'ryanpeikou': ['chiitoitsu'],` 就不需要 `'chiitoitsu': ['ryanpeikou'],` ？

役滿也有個 Compatibility table，我們需要嗎？

**Comment by rasca0027** [comment]
應該是不需要反過來（幫我檢查一下邏輯XD）
役滿的我感覺不用，因為已經有max 兩倍役滿

**Comment by ktc312** [comment]
# Not sure what '-' is...
        # IPP
        # SMO
        # TAN
        # PFU
        # IPK
        # ITT / TAN
        # YAK / TAN, PFU
        # SDJ / ITT
        # SDO / PFU, IPK, ITT, SDJ
        # TOI / PFU, IPK, ITT, SDJ
        # SNA / PFU, IPK, ITT, SDJ
        # SNK / PFU, IPK, ITT, SDJ
        # CHA / TAN, ITT
        # JUN / TAN, ITT, YAK
        # RPK / IPK, ITT, YAK, SDJ, SDO, TOI, SNA, SNK
        # SSG / TAN, PFU, ITT, SDJ, SDO, JUN, RPK
        # HRO / TAN, PFU, IPK, ITT, SDJ, CHA, RPK
        # HON / SDJ, SDO
        # CHN / YAK, SDJ, SDO, SSG, HRO, HON
        # CHI / PFU, IPK, ITT, YAK, SDJ, SDO, TOI, SNA, SNK, JUN, RPK, SSG
        # RIN / IPP, PFU, RPK, CHI
        # HAI / RIN
        # HOU / IPP, SMO, RIN, HAI
        # CHK / SMO, TOI, RPK, HRO, CHI, RIN, HAI, HOU
